backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "content/home.json"
        label: "Home Content"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Description", name: "hero_desc", widget: "text" }
